---
title: "DM Group 19"
author: "Mina Narayanan"
date: "5/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ISLR)
library(MASS)
library(klaR) 
library(knitr)
library(glmnet)
library(gam)
library(plyr)
library(reshape)
library(boot)
library(survival)
library(ggfortify)
```

# To filter compas two years

Subset of columns used in original analysis are:
raw_data, age, c_charge_degree, race, age_cat, score_text, sex, priors_count, days_b_screening_arrest, decile_score, is_recid, two_year_recid, c_jail_in, c_jail_out

```{r}
raw_data <- read.csv("./compas-scores-two-years.csv")
nrow(raw_data)

compas_non_violent <- raw_data %>% 
  filter(days_b_screening_arrest <= 30) %>%
  filter(days_b_screening_arrest >= -30) %>%
  filter(is_recid != -1) %>%
  filter(c_charge_degree != "O") %>%
  filter(score_text != 'N/A')
nrow(compas_non_violent)

compas_non_violent <- mutate(compas_non_violent, crime_factor = factor(c_charge_degree)) %>%
      mutate(age_factor = as.factor(age_cat)) %>%
      within(age_factor <- relevel(age_factor, ref = 1)) %>%
      mutate(race_factor = factor(race)) %>%
      within(race_factor <- relevel(race_factor, ref = 3)) %>%
      mutate(gender_factor = factor(sex, labels= c("Female","Male"))) %>%
      within(gender_factor <- relevel(gender_factor, ref = 2)) %>%
      mutate(score_factor = factor(score_text != "Low", labels = c("LowScore","HighScore")))



# Read in cox-parsed csv file
cox_parsed <- read.csv("./cox-parsed.csv")
```


# LDA Analysis
```{r}
# Feature selection/see what variables are important/build density plots

# Check for correlation between input variables
compas.var.names <- c("priors_count", "juv_fel_count", "juv_misd_count", "juv_other_count")
pairs(compas_non_violent[,compas.var.names])
round(cor(compas_non_violent[,compas.var.names]), 3)

# Function taken from ?pairs Example section.  
panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...)
{
    usr <- par("usr"); on.exit(par(usr))
    par(usr = c(0, 1, 0, 1))
    r <- abs(cor(x, y))
    txt <- format(c(r, 0.123456789), digits = digits)[1]
    txt <- paste0(prefix, txt)
    if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)
    text(0.5, 0.5, txt, cex = pmax(1, cex.cor * r))
}

# Use panel.cor to display correlations in lower panel
# No obvious correlation between any predictors, which is good
pairs(compas_non_violent[,compas.var.names], lower.panel = panel.cor)

# Create train and test datasets
index = sample( 1:nrow( compas_non_violent ), round( nrow( compas_non_violent )*0.6 ), replace = FALSE )
train = compas_non_violent[ index, ] # About 60% of the observations
test = compas_non_violent[ -index, ] # About 40% of the observations

# NONVIOLENT LDA MODEL
nonviolent.lda <- lda(is_recid ~ gender_factor + age_factor + race_factor + crime_factor + priors_count + juv_fel_count + juv_misd_count + juv_other_count, data=train)
nonviolent.lda
nonviolent.lda.train = predict(nonviolent.lda, type="response")
tab <- table(nonviolent.lda.train$class, train$is_recid)
tab

# Training Accuracy for Nonviolent LDA model is 2490/3703 = 67.243% (optimistic estimate)

# Test the Nonviolent LDA model
nonviolent.lda.test = predict(nonviolent.lda, newdata=test)
tab <- table(nonviolent.lda.test$class, test$is_recid)
tab

# Test Accuracy for Nonviolent LDA model is 1652/2469 = 66.910% (note that this is less than the training accuracy)

# TODO: Determine whether nonviolent lda model is equally predictive across race, age, and gender


 
# VIOLENT LDA MODEL
violent.lda <- lda(is_violent_recid ~ gender_factor + age_factor + race_factor + crime_factor + priors_count + juv_fel_count + juv_misd_count + juv_other_count, data=train)
violent.lda
violent.lda.train = predict(violent.lda, type="response")
tab <- table(violent.lda.train$class, train$is_recid)
tab

# Training Accuracy for Violent LDA model is 1947/3703 = 52.579% (optimistic estimate)

# Test the Violent LDA model
violent.lda.test = predict(violent.lda, newdata=test)
tab <- table(violent.lda.test$class, test$is_recid)
tab

# Test Accuracy for Violent LDA model is 1254/2469 = 50.790% (note that this is less than the training accuracy)


# TODO: Determine whether violent lda model is equally predictive across race, age, and gender




# Run a Cox model to compare the accuracy of LDA models to COMPAS' model

# Create new dataframe test_with_labels that appends labels to test dataframe
test_with_labels <- test
test_with_labels$nonviolent_lda_labels = nonviolent.lda.test$class
test_with_labels$violent_lda_labels = violent.lda.test$class

# Write lda predictions to cox-parsed-lda.csv 
cox_parsed_lda = cox_parsed[FALSE,]
for (i in (1: nrow(test_with_labels))) {
  new_rows <- subset(cox_parsed, name == as.character(test_with_labels[i,]$name))
  new_rows$non_violent_lda_labels = test_with_labels[i, ]$nonviolent_lda_labels
  new_rows$violent_lda_labels = test_with_labels[i, ]$violent_lda_labels
  cox_parsed_lda <- rbind(cox_parsed_lda, new_rows)
}


write.csv(cox_parsed_lda, "cox-parsed-lda.csv")

data <- filter(filter(read.csv("./cox-parsed-lda.csv"), score_text != "N/A"), end > start) %>%
        mutate(race_factor = factor(race,
                                  labels = c("African-American", 
                                             "Asian",
                                             "Caucasian", 
                                             "Hispanic", 
                                             "Native American",
                                             "Other"))) %>%
        within(race_factor <- relevel(race_factor, ref = 3)) %>%
        mutate(score_factor = factor(score_text)) %>%
        within(score_factor <- relevel(score_factor, ref=2)) %>%
        mutate(non_violent_score_factor = factor(non_violent_lda_labels)) %>%
        within(non_violent_score_factor <- relevel(non_violent_score_factor, ref = 1)) %>%
        mutate(violent_score_factor = factor(violent_lda_labels)) %>%
        within(violent_score_factor <- relevel(violent_score_factor, ref = 1))
    

f <- Surv(start, end, event, type="counting") ~ non_violent_score_factor
nonviolent_model <- coxph(f, data=data)
summary(nonviolent_model)
# Nonviolent LDA model has a concordance of 62.3%
# COMPAS system's concordance is 63.6%

f <- Surv(start, end, event, type="counting") ~ violent_score_factor
violent_model <- coxph(f, data=data)
summary(violent_model)
# Violent LDA model has a concordance of 50.2%
# COMPAS's violent recidivism score has a concordance score of 65.1%



```

# QDA
```{r}
# Nonviolent
nonviolent.qda <- qda(score_text ~ sex_num + age + race_num + c_charge_degree + priors_count + two_year_recid + juv_fel_count + juv_misd_count + juv_other_count, data=compas_non_violent)
nonviolent.qda
qda.probs=predict(nonviolent.qda,type="response")
ct <- table(compas_non_violent$score_text, qda.probs$class)
ct
# Accuracy is 3843/6172 = 62.265%
# COMPAS system's concordance is 63.6%

graphics.off()
par("mar")
par(mar=c(1,1,1,1))
partimat(score_text ~ sex_num + age + race_num + c_charge_degree + priors_count + two_year_recid + juv_fel_count + juv_misd_count + juv_other_count, data=compas_non_violent, method="qda", plot.matrix=TRUE)


# Violent
violent.qda <- qda(v_score_text ~ sex_num + age + race_num + c_charge_degree + priors_count + two_year_recid + juv_fel_count + juv_misd_count + juv_other_count, data=compas_non_violent)
violent.qda
qda.probs=predict(violent.qda,type="response")
ct <- table(compas_non_violent$v_score_text, qda.probs$class)
ct
# Accuracy is 4212/6172 = 68.244%
# COMPAS's violent recidivism score has a slightly higher overall concordance score of 65.1%

```

# Naive Bayes
```{r}
# Nonviolent 
nonviolent.nb <- NaiveBayes(score_text ~ sex_num + age + race_num + c_charge_degree + priors_count + two_year_recid + juv_fel_count + juv_misd_count + juv_other_count, data=compas_non_violent, usekernel=TRUE)
bayes.probs=predict(nonviolent.nb, type="response")
out <- table(compas_non_violent$score_text, bayes.probs$class)
out
# Accuracy of 3560/6127 = 58.103%
# COMPAS system's concordance is 63.6%

# Violent
violent.nb <- NaiveBayes(v_score_text ~ sex_num + age + race_num + c_charge_degree + priors_count + two_year_recid + juv_fel_count + juv_misd_count + juv_other_count, data=compas_non_violent, usekernel=TRUE)
bayes.probs=predict(violent.nb, type="response")
out <- table(compas_non_violent$v_score_text, bayes.probs$class)
out
# Accuracy of 4166/6127 = 67.994%
# COMPAS's violent recidivism score has a slightly higher overall concordance score of 65.1%
```


# RAI
```{r}
rai <- function(type=c("lda", "qda", "bayes", "rf", "dec", "reg")) {
  type <- match.arg(type)
  if (type == "lda") {
  }
}
```






